### ISSUE TITLE
Build fails with error: field ‘ipc’ has incomplete type

### ISSUE THREAD

**Issue by eternal-sorrow** [tadeokondrak/anthywl#21]
I'm trying to build anthywl on my Gentoo system. I get this error from build. Here's a whole build log from portage: https://0x0.st/ohp1.txt

There might be something wrong with my ebuild, then then please tell me how to build it correctly.

**Comment by tadeokondrak** [comment]
Could you try https://github.com/tadeokondrak/anthywl/commit/10f18f9a880a0897cb65ff778d8605101a612183?

**Comment by eternal-sorrow** [comment]
Yep, that builds. Thank you.
