### ISSUE TITLE
nuke wl_list

### ISSUE THREAD

**Issue by mozartilize** [tadeokondrak/anthywl#6]
the code need updated after this https://github.com/swaywm/wlroots/pull/3002

**Comment by tadeokondrak** [comment]
Hi, that issue is about wlr_list, which is part of wlroots, but this code does not use wlroots. This code uses wl_list, which is part of libwayland.

On July 1, 2021 12:22:20 p.m. MDT, mozartilize ***@***.***> wrote:
>the code need updated after this
>https://github.com/swaywm/wlroots/pull/3002
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tadeokondrak/anthywl/issues/6

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mozartilize** [comment]
thanks, didn't know about that
